### ISSUE TITLE
`module.parent` is deprecated since node@14.6.0

### ISSUE THREAD

**Issue by richardguerre** [relay-tools/relay-graphql-js#21]
In `generate-config/src/dependencies.ts` the `moduleFromDependencyModules` function tries to use `module.parent` to find `graphql.vscode-graphql`'s node_modules. 

`module.parent` is deprecated on node version 14.6.0 and later, and it throws `Error: Unable to find graphql.vscode-graphql's node_modules` on those versions.

All that needs to change is line 28:
```diff
- mod = module.parent!;
+ mod = Object.values(require.cache).filter((m) => m.children.includes(module))[0];
```

**Comment by acao** [comment]
hey i can add this fix my bad! just seeing this now

**Comment by acao** [comment]
CC @orta weren't you asking about how we could load the user's `graphql-js` version? I think this is what we need.

**Comment by acao** [comment]
Finally working with relay tools and I love the new compiler, but I want to make we get this up to par!
